### ISSUE TITLE
the best model selection

### ISSUE THREAD

**Issue by catherine-qian** [nikhilsinghmus/room2reverb#26]
Dear authors,

Could you please let me know how you select the best model?
From the validation set? or report the best test results in the paper?

BTW, have you tried to remove the adversarial scheme to see the results with only a generator?

**Comment by nikhilsinghmus** [comment]
Hi! Yes, we just used test set performance as in the paper. We didn’t do early stopping or similar, generally.

Early on we had tried a non-adversarial approach but found it difficult to get good results so didn’t include it in the ablations later, if I remember correctly. Could definitely be worth revisiting though, because we did make other improvements since then.

**Comment by catherine-qian** [comment]
thanks for the prompt reply!
