### ISSUE TITLE
large, medium, small label

### ISSUE THREAD

**Issue by catherine-qian** [nikhilsinghmus/room2reverb#30]
Dear authors, 
just wonder whether you have the label for the size of the scene？ such as large, small, medium, indoor, outdoor

**Comment by nikhilsinghmus** [comment]
Hi, thank you for the question! Unfortunately, I'm not sure we stored the individual labels for all the data. As I recall, the strategy we used was to first sort by labelling Places365 classes, then sample and check (can see scripts/training_distribution.py and scripts/label_categories.py for some parts of this). Given some time, I can likely make these; let me know if that would be useful to you.

I believe we may also have an indoor-only dataset variant from our early experiments, although I'm not sure if it is complete since we may have added more data sources. Glad to share in any case, since it might help to infer indoor/outdoor labels more quickly.

**Comment by catherine-qian** [comment]
Dear authors,

Thanks for your quick reply.
For the indoor, outdoor label, I can annotate them by myself since it is straightforward to see.

Besides, I saw you use RT60 to measure the reverberation influence. There are also other paramters for reverberatiom measurement, such as DRR and EDT. Have you ever used that?
(I am trying to compute DRR and EDT from impulse reponse  but didn't find avaliable python script)

**Comment by nikhilsinghmus** [comment]
No problem! We initially computed them, but since we don't have source or mic position, felt the results were difficult to interpret. We computed these with matlab, and you can find the scripts under scripts/matlab_scripts. Also, the same python library we use for t60 estimation can also estimate EDT given an optional argument (also T20 and T30 etc.) as well as CTE.

For DRR, I think one could port from [here](https://github.com/IoSR-Surrey/MatlabToolbox/blob/master/%2Biosr/%2Bacoustics/irStats.m), but have not tried yet. Also the python-acoustics CTE implementation could also be pretty helpful, I think.

**Comment by catherine-qian** [comment]
thanks for the reply!
